# Generated by Django 6.0.1 on 2026-01-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeuSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
